name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    # Backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
